cd %userprofile%\Desktop
mkdir res
cd res
echo ############################################################################################# >> "1.ver.txt"
echo "ver" >> "1.ver.txt"
ver >> "1.ver.txt"
echo ############################################################################################# >> "2.path.txt"
echo "path" >> "2.path.txt"
path >> "2.path.txt"
echo ############################################################################################# >> "3.assoc.txt"
echo "assoc" >> "3.assoc.txt"
assoc >> "3.assoc.txt"
echo ############################################################################################# >> "4.Wmic process get.txt"
echo "Wmic process get ExecutablePath,processid,parentprocessid,commandline /format:textvaluelist" >> "4.Wmic process get.txt"
Wmic process get ExecutablePath,processid,parentprocessid,commandline /format:textvaluelist >> "4.Wmic process get.txt"
echo ############################################################################################# >> "5.date-t.txt"
echo "date /t" >> "5.date-t.txt"
date /t >> "5.date-t.txt"
echo ############################################################################################# >> "6.wmic-node.txt"
echo "wmic /node:localhost product list full /format:textvaluelist" >> "6.wmic-node.txt"
wmic /node:localhost product list full /format:textvaluelist >> "6.wmic-node.txt"
echo ############################################################################################# >> "7.wmic product get.txt"
echo "wmic product get name,version /format:textvaluelist" >> "7.wmic product get.txt"
wmic product get name,version /format:textvaluelist >> "7.wmic product get.txt"
echo ############################################################################################# >> "8.tree C.txt"
echo "tree C:\ /F" >> "8.tree C.txt"
tree C:\ /F >> "8.tree C.txt"
echo ############################################################################################# >> "9.tasklist -v.txt"
echo "tasklist -v" >> "9.tasklist -v.txt"
tasklist -v >> "9.tasklist -v.txt"
echo ############################################################################################# >> "10.wmic process list full.txt"
echo "wmic process list full /format:textvaluelist" >> "10.wmic process list full.txt"
wmic process list full /format:textvaluelist >> "10.wmic process list full.txt"
echo ############################################################################################# >> "11.whoami -all.txt"
echo "whoami /all" >> "11.whoami -all.txt"
whoami /all >> "11.whoami -all.txt"
echo ############################################################################################# >> "12.ipconfig -all.txt"
echo "ipconfig /all" >> "12.ipconfig -all.txt"
ipconfig /all >> "12.ipconfig -all.txt"
echo ############################################################################################# >> "13.arp -a.txt"
echo "arp -a" >> "13.arp -a.txt"
arp -a >> "13.arp -a.txt"
echo ############################################################################################# >> "14.tasklist -svc.txt"
echo "tasklist /svc" >> "14.tasklist -svc.txt"
tasklist /svc >> "14.tasklist -svc.txt"
echo ############################################################################################# >> "15.sc query.txt"
echo "sc query state=all" >> "15.sc query.txt"
sc query state=all >> "15.sc query.txt"
echo ############################################################################################# >> "16.net start.txt"
echo "net start" >> "16.net start.txt"
net start >> "16.net start.txt"
echo ############################################################################################# >> "17.net use.txt"
echo "net use" >> "17.net use.txt"
net use >> "17.net use.txt"
echo ############################################################################################# >> "18.net share.txt"
echo "net share" >> "18.net share.txt"
net share >> "18.net share.txt"
echo ############################################################################################# >> "19.net session.txt"
echo "net session" >> "19.net session.txt"
net session >> "19.net session.txt"
echo ############################################################################################# >> "20.net localgroup.txt"
echo "net localgroup" >> "20.net localgroup.txt"
net localgroup >> "20.net localgroup.txt"
echo ############################################################################################# >> "21.net localgroup administrators.txt"
echo "net localgroup administrators" >> "21.net localgroup administrators.txt"
net localgroup administrators >> "21.net localgroup administrators.txt"
echo ############################################################################################# >> "22.net localgroup remote desktop.txt"
echo "net localgroup "Remote desktop users"" >> "22.net localgroup remote desktop.txt"
net localgroup "Remote desktop users" >> "22.net localgroup remote desktop.txt"
echo ############################################################################################# >> "23.net view.txt"
echo "net view" >> "23.net view.txt"
net view >> "23.net view.txt"
echo ############################################################################################# >> "24.net view -domain.txt"
echo "net view /domain" >> "24.net view -domain.txt"
net view /domain >> "24.net view -domain.txt"
echo ############################################################################################# >> "25.net user.txt"
echo "net user" >> "25.net user.txt"
net user >> "25.net user.txt"
echo ############################################################################################# >> "26.net user -domain.txt"
echo "net user /domain" >> "26.net user -domain.txt"
net user /domain >> "26.net user -domain.txt"
echo ############################################################################################# >> "27.net group.txt"
echo "net group" >> "27.net group.txt"
net group >> "27.net group.txt"
echo ############################################################################################# >> "28.net group -domain.txt"
echo "net group /domain" >> "28.net group -domain.txt"
net group /domain >> "28.net group -domain.txt"
echo ############################################################################################# >> "29.wmic useraccount get name.txt"
echo "Wmic useraccount get name /format:textvaluelist" >> "29.wmic useraccount get name.txt"
Wmic useraccount get name /format:textvaluelist >> "29.wmic useraccount get name.txt"
echo ############################################################################################# >> "30.wmic useraccount list.txt"
echo "wmic useraccount list /format:textvaluelist" >> "30.wmic useraccount list.txt"
wmic useraccount list /format:textvaluelist >> "30.wmic useraccount list.txt"
echo ############################################################################################# >> "31.wmic startup list full.txt"
echo "wmic startup list full /format:textvaluelist" >> "31.wmic startup list full.txt"
wmic startup list full /format:textvaluelist >> "31.wmic startup list full.txt"
echo ############################################################################################# >> "32.wmic startup list brief.txt"
echo "wmic startup list brief /format:textvaluelist" >> "32.wmic startup list brief.txt"
wmic startup list brief /format:textvaluelist >> "32.wmic startup list brief.txt"
echo ############################################################################################# >> "33.wmic share list brief.txt"
echo "Wmic share list brief /format:textvaluelist" >> "33.wmic share list brief.txt"
Wmic share list brief /format:textvaluelist >> "33.wmic share list brief.txt"
echo ############################################################################################# >> "34.Schtasks -query -fo.txt"
echo "Schtasks /query /fo LIST /v" >> "34.Schtasks -query -fo.txt"
Schtasks /query /fo LIST /v >> "34.Schtasks -query -fo.txt"
echo ############################################################################################# >> "35.Schtasks -v.txt"
echo "Schtasks -v" >> "35.Schtasks -v.txt"
Schtasks -v >> "35.Schtasks -v.txt"
echo ############################################################################################# >> "36.dir -s -b temp.txt"
echo "dir /s /b %TEMP% | findstr /e .exe" >> "36.dir -s -b temp.txt"
dir /s /b %TEMP% | findstr /e .exe >> "36.dir -s -b temp.txt"
echo ############################################################################################# >> "37.bitsadmin -list -allusers.txt"
echo "bitsadmin /list /allusers /verbose" >> "37.bitsadmin -list -allusers.txt"
bitsadmin /list /allusers /verbose >> "37.bitsadmin -list -allusers.txt"
echo ############################################################################################# >> "38.ipconfig -displaydns.txt"
echo "ipconfig /displaydns" >> "38.ipconfig -displaydns.txt"
ipconfig /displaydns >> "38.ipconfig -displaydns.txt"
echo ############################################################################################# >> "39.netstat -nat.txt"
echo "netstat -nat" >> "39.netstat -nat.txt"
netstat -nat >> "39.netstat -nat.txt"
echo ############################################################################################# >> "40.netstat -anbo.txt"
echo "netstat -anbo" >> "40.netstat -anbo.txt"
netstat -anbo >> "40.netstat -anbo.txt"
echo ############################################################################################# >> "41.netstat -r.txt"
echo "netstat -r" >> "41.netstat -r.txt"
netstat -r >> "41.netstat -r.txt"
echo ############################################################################################# >> "42.quser.txt"
echo "quser" >> "42.quser.txt"
quser >> "42.quser.txt"
echo ############################################################################################# >> "43.dnscmd -enum zones.txt"
echo "dnscmd /enum zones" >> "43.dnscmd -enum zones.txt"
dnscmd /enumzones >> "43.dnscmd -enum zones.txt"
echo ############################################################################################# >> "44.systeminfo.txt"
echo "systeminfo" >> "44.systeminfo.txt"
systeminfo >> "44.systeminfo.txt"
echo ############################################################################################# >> "45.nslookup myip.opendns.com resolver1.opendns.com.txt"
echo "nslookup myip.opendns.com resolver1.opendns.com" >> "45.nslookup myip.opendns.com resolver1.opendns.com.txt"
nslookup myip.opendns.com resolver1.opendns.com >> "45.nslookup myip.opendns.com resolver1.opendns.com.txt"
echo ############################################################################################# >> "46.curl checkip.amazonaws.com.txt"
echo "curl checkip.amazonaws.com" >> "46.curl checkip.amazonaws.com.txt"
curl checkip.amazonaws.com >> "46.curl checkip.amazonaws.com.txt"
echo ############################################################################################# >> "47.ping -n 1.txt"
echo "ping -n 1 8.8.8.8" >> "47.ping -n 1.txt"
ping -n 1 8.8.8.8 >> "47.ping -n 1.txt"
echo ############################################################################################# >> "48.Reg query RecentDocs.txt"
echo "Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs"" >> "48.Reg query RecentDocs.txt"
reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs" >> "48.Reg query RecentDocs.txt"
echo ############################################################################################# >> "49.Reg query UserAssist.txt"
echo "Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist"" >> "49.Reg query UserAssist.txt"
Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\UserAssist" >> "49.Reg query UserAssist.txt"
echo ############################################################################################# >> "50.Reg query RunOnce.txt"
echo "reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce"" >> "50.Reg query RunOnce.txt"
reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" >> "50.Reg query RunOnce.txt"
echo ############################################################################################# >> "51.Reg query Run.txt"
echo "reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"" >> "51.Reg query Run.txt"
reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" >> "51.Reg query Run.txt"
echo ############################################################################################# >> "52.Reg query RunMRU.txt"
echo "Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\RunMRU"" >> "52.Reg query RunMRU.txt"
Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\RunMRU" >> "52.Reg query RunMRU.txt"
echo ############################################################################################# >> "53.Reg query FileExts.txt"
echo "Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts"" >> "53.Reg query FileExts.txt"
Reg query "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts" >> "53.Reg query FileExts.txt"
echo ############################################################################################# >> "54.Reg query USBSTOR.txt"
echo "Reg query "HKLM\SYSTEM\CurrentControlSet\Enum\USBSTOR\" /s" >> "54.Reg query USBSTOR.txt"
reg query "HKLM\SYSTEM\CurrentControlSet\Enum\USBSTOR\ /s" >> "54.Reg query USBSTOR.txt"
echo ############################################################################################# >> "55.Reg query USB.txt"
echo "Reg query "HKLM\SYSTEM\CurrentControlSet\Enum\USBS\" /s" >> "55.Reg query USB.txt"
reg query "HKLM\SYSTEM\CurrentControlSet\Enum\USB\" /s >> "55.Reg query USB.txt"
echo #############################################################################################
copy C:\Windows\System32\winevt\Logs\Security.evtx "%userprofile%\Desktop\res\Security.evtx"
echo #############################################################################################
copy "C:\Windows\System32\winevt\Logs\Windows PowerShell.evtx" "%userprofile%\Desktop\res\Windows PowerShell.evtx"
echo #############################################################################################
copy "C:\Windows\System32\winevt\Logs\Microsoft-Windows-RemoteDesktopServices-RdpCoreTS%4Admin.evtx" "%userprofile%\Desktop\res\Microsoft-Windows-RemoteDesktopServices-RdpCoreTS%4Admin.evtx"
echo #############################################################################################
copy "C:\Windows\System32\winevt\Logs\Microsoft-Windows-RemoteDesktopServices-RemoteFX-Synth3dvsc%4Admin.evtx" "%userprofile%\Desktop\res\Microsoft-Windows-RemoteDesktopServices-RemoteFX-Synth3dvsc%4Admin.evtx"
echo #############################################################################################
copy "C:\Windows\System32\winevt\Logs\Microsoft-Windows-RemoteDesktopServices-SessionServices%4Operational.evtx" "%userprofile%\Desktop\res\Microsoft-Windows-RemoteDesktopServices-SessionServices%4Operational.evtx"
echo #############################################################################################
type "1.ver.txt" >> "0.all-res.txt"
type "2.path.txt" >> "0.all-res.txt"
type "3.assoc.txt" >> "0.all-res.txt"
type "4.Wmic process get.txt" >> "0.all-res.txt"
type "5.date-t.txt" >> "0.all-res.txt"
type "6.wmic-node.txt" >> "0.all-res.txt"
type "7.wmic product get.txt" >> "0.all-res.txt"
type "8.tree C.txt" >> "0.all-res.txt"
type "9.tasklist -v.txt" >> "0.all-res.txt"
type "10.wmic process list full.txt" >> "0.all-res.txt"
type "11.whoami -all.txt" >> "0.all-res.txt"
type "12.ipconfig -all.txt" >> "0.all-res.txt"
type "13.arp -a.txt" >> "0.all-res.txt"
type "14.tasklist -svc.txt" >> "0.all-res.txt"
type "15.sc query.txt" >> "0.all-res.txt"
type "16.net start.txt" >> "0.all-res.txt"
type "17.net use.txt" >> "0.all-res.txt"
type "18.net share.txt" >> "0.all-res.txt"
type "19.net session.txt" >> "0.all-res.txt"
type "20.net localgroup.txt" >> "0.all-res.txt"
type "21.net localgroup administrators.txt" >> "0.all-res.txt"
type "22.net localgroup remote desktop.txt" >> "0.all-res.txt"
type "23.net view.txt" >> "0.all-res.txt"
type "24.net view -domain.txt" >> "0.all-res.txt"
type "25.net user.txt" >> "0.all-res.txt"
type "26.net user -domain.txt" >> "0.all-res.txt"
type "27.net group.txt" >> "0.all-res.txt"
type "28.net group -domain.txt" >> "0.all-res.txt"
type "29.wmic useraccount get name.txt" >> "0.all-res.txt"
type "30.wmic useraccount list.txt" >> "0.all-res.txt"
type "31.wmic startup list full.txt" >> "0.all-res.txt"
type "32.wmic startup list brief.txt" >> "0.all-res.txt"
type "33.wmic share list brief.txt" >> "0.all-res.txt"
type "34.Schtasks -query -fo.txt" >> "0.all-res.txt"
type "35.Schtasks -v.txt" >> "0.all-res.txt"
type "36.dir -s -b temp.txt" >> "0.all-res.txt"
type "37.bitsadmin -list -allusers.txt" >> "0.all-res.txt"
type "38.ipconfig -displaydns.txt" >> "0.all-res.txt"
type "39.netstat -nat.txt" >> "0.all-res.txt"
type "40.netstat -anbo.txt" >> "0.all-res.txt"
type "41.netstat -r.txt" >> "0.all-res.txt"
type "42.quser.txt" >> "0.all-res.txt"
type "43.dnscmd -enum zones.txt" >> "0.all-res.txt"
type "44.systeminfo.txt" >> "0.all-res.txt"
type "45.nslookup myip.opendns.com resolver1.opendns.com.txt" >> "0.all-res.txt"
type "46.curl checkip.amazonaws.com.txt" >> "0.all-res.txt"
type "47.ping -n 1.txt" >> "0.all-res.txt"
type "48.Reg query RecentDocs.txt" >> "0.all-res.txt"
type "49.Reg query UserAssist.txt" >> "0.all-res.txt"
type "50.Reg query RunOnce.txt" >> "0.all-res.txt"
type "51.Reg query Run.txt" >> "0.all-res.txt"
type "52.Reg query RunMRU.txt" >> "0.all-res.txt"
type "53.Reg query FileExts.txt" >> "0.all-res.txt"
type "54.Reg query USBSTOR.txt" >> "0.all-res.txt"
type "55.Reg query USB.txt" >> "0.all-res.txt"
echo #############################################################################################
pause